# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - awesomo-bot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Mundane Fixes 🦄
      labels:
        - Semver-Patch
        - bug-fixes
    - title: Other Changes
      labels:
        - "*"
